name: identification-service

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: dev
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/admin`) || PathPrefix(`/api`) || PathPrefix(`/accounts`) || PathPrefix(`/_allauth`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.tls=false"
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend:/home/web/code

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: dev
    labels:
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.tls=false"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
    env_file:
      - ./frontend/.env
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
