name: identification-service

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/home/web/code

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./frontend/.env
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html

  proxy:
    command:
      - "--api.insecure=True"